FROM hiroshiba/hiho-docker-base:v6.2

# install for audio utils, librosa, segmentation-kit
RUN apt-get update && \
    apt-get install -y sox ffmpeg julius && \
    apt-get install -y open-jtalk open-jtalk-mecab-naist-jdic hts-voice-nitech-jp-atr503-m001 && \
    apt-get install -y swig libsndfile1-dev libasound2-dev && \
    apt-get install -y perl pulseaudio build-essential && \
    apt-get install -y icu-devtools && \
    apt-get clean

# github
WORKDIR /github

# dictation-kit
RUN id=1ceb4dec245ef482918ca33c55c71d383dce145e && \
    curl -kL https://github.com/julius-speech/dictation-kit/archive/$id.zip > /tmp/github.zip && \
    unzip /tmp/github.zip -d /github/ && \
    mv /github/dictation-kit* /github/dictation-kit && \
    curl -kL https://github.com/julius-speech/dictation-kit/raw/$id/model/phone_m/jnas-mono-16mix-gid.binhmm > /github/dictation-kit/model/phone_m/jnas-mono-16mix-gid.binhmm && \
    curl -kL https://github.com/julius-speech/dictation-kit/raw/$id/model/phone_m/jnas-tri-3k16-gid.binhmm > /github/dictation-kit/model/phone_m/jnas-tri-3k16-gid.binhmm && \
    curl -kL https://github.com/julius-speech/dictation-kit/raw/$id/model/phone_m/logicalTri > /github/dictation-kit/model/phone_m/logicalTri && \
    curl -kL https://github.com/julius-speech/dictation-kit/raw/$id/model/phone_m/logicalTri-3k16-gid.bin > /github/dictation-kit/model/phone_m/logicalTri-3k16-gid.bin && \
    rm /tmp/github.zip

# segmentation-kit
RUN curl -kL https://github.com/Hiroshiba/segmentation-kit/archive/4b23e4b40acbf301731022a54aadad5a197ab2aa.zip > /tmp/github.zip && \
    unzip /tmp/github.zip -d /github/ && \
    mv /github/segmentation-kit* /github/segmentation-kit && \
    rm /tmp/github.zip

# pypi
RUN pip install \
  librosa==0.7.2 \
  ffmpeg-python \
  git+https://github.com/Hiroshiba/acoustic_feature_extractor@77da05bb702b76fa2130037471448343259f84c5 \
  git+https://github.com/Hiroshiba/openjtalk-label-getter@f355987682009da22ec812b2a56a438d68fcbce6 \
  git+https://github.com/Hiroshiba/julius4seg@0e01f546bf4aa1329c9ee7a39df8630c066e63e3

WORKDIR /root
