FROM hiroshiba/hiho-docker-base:v1

# install for audio utils, librosa, segmentation-kit
RUN apt-get update && \
    apt-get install -y sox ffmpeg julius && \
    apt-get install -y swig libsndfile1-dev libasound2-dev && \
    apt-get install -y perl pulseaudio build-essential && \
    apt-get clean

# pypi
RUN pip install librosa==0.7.2
RUN pip install git+https://github.com/Hiroshiba/acoustic_feature_extractor@25892fcccb41276e7169858d59eb17e1f9217015

# github
WORKDIR /github

RUN curl -kL https://github.com/julius-speech/dictation-kit/archive/1ceb4dec245ef482918ca33c55c71d383dce145e.zip > /tmp/github.zip && \
    unzip /tmp/github.zip -d /github/ && \
    mv /github/dictation-kit* /github/dictation-kit && \
    rm /tmp/github.zip

RUN curl -kL https://github.com/Hiroshiba/segmentation-kit/archive/4b23e4b40acbf301731022a54aadad5a197ab2aa.zip > /tmp/github.zip && \
    unzip /tmp/github.zip -d /github/ && \
    mv /github/segmentation-kit* /github/segmentation-kit && \
    rm /tmp/github.zip

WORKDIR /root
