FROM ubuntu:18.04

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing && \
    apt-get install -y \
      wget \
      bzip2 \
      ca-certificates \
      curl \
      git \
      gcc \
      g++ \
      cmake \
      sudo \
      htop \
      jq \
      vim \
      tree \
      dstat \
      parallel \
      git-lfs \
      unzip \
      && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# kubernetes
RUN apt-get update && \
    apt-get install -y apt-transport-https gnupg && \
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list && \
    apt-get update && \
    apt-get install -y kubectl

# miniconda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.7.12-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN conda install -y python=3.7.5

# conda
RUN conda install -y \
      numpy \
      numba

# pypi
RUN pip install \
      scipy \
      pandas \
      matplotlib \
      ipython \
      jupyter \
      mypy \
      pytest \
      yq \
      gpustat

# ssh
RUN apt-get update && apt-get install -y openssh-server openssh-client wget && \
    apt-get clean && mkdir /var/run/sshd

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh && \
    echo "wget --quiet \$GITHUB_KEYS -O /root/.ssh/authorized_keys" > /run.sh && \
    echo "chmod 600 /root/.ssh/authorized_keys" >> /run.sh && \
    echo "/usr/sbin/sshd -D" >> /run.sh

EXPOSE 22
CMD ["/bin/bash", "/run.sh"]
