name: "Setup Docker"
description: "QEMU、Docker Buildx、Docker Hub Login のセットアップ"

inputs:
  dockerhub_username:
    description: "Docker Hub username"
    required: true
  dockerhub_token:
    description: "Docker Hub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
