name: "Setup Docker"
description: "QEMU、Docker Buildx、Docker Hub Login のセットアップ"

inputs:
  dockerhub_username:
    description: "Docker Hub username"
    required: true
  dockerhub_token:
    description: "Docker Hub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Clean Disk Space
      shell: bash
      run: |
        echo "Removing large pre-installed tools..."
        # .NET SDKs
        sudo rm -rf /usr/share/dotnet
        # Haskell (ghc)
        sudo rm -rf /opt/ghc /usr/local/.ghcup
        # Android SDK/NDK
        sudo rm -rf /usr/local/lib/android
        # CodeQL
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        # Swift
        sudo rm -rf /usr/share/swift
        # Go
        sudo rm -rf /usr/local/go /opt/hostedtoolcache/go
        # Java (OpenJDK)
        sudo rm -rf /usr/lib/jvm/*
        # Ruby tool cache and rvm
        sudo rm -rf /opt/hostedtoolcache/Ruby /home/runner/.rvm

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
